name: ngramwavenet_pytorch
project: conv
workspace: aamu2908
hyperparameters:
  n_embed:
    type: int
    minval: 32
    maxval: 128
  embed_weight_data:
    type: double
    minval: 0.05
    maxval: 0.2
  block_size: 8
  learning_rate: 
    type: double
    maxval: 0.1
    minval: 0.001
  n_hidden:
    type: int
    minval: 64
    maxval: 256
  dropout:
    type: double
    minval: 0.0
    maxval: 0.6
  linear_weight_data:
    type: double
    minval: 0.05
    maxval: 0.2
  lr_momentum:
    type: double
    minval: 0.0
    maxval: 0.99
  lr_weight_decay:
    type: log
    minval: -5.0
    maxval: -2.0
    base: 10
searcher:
  name: adaptive_asha
  metric: validation_loss
  smaller_is_better: true
  max_trials: 16
  max_length:
    batches: 10000 #60,000 training images with batch size 64
resources:
  resource_pool: gpu
entrypoint: python3 train_conv.py